### ISSUE TITLE
getInfoFromName don't work

### ISSUE THREAD

**Issue by xdk78** [Kylart/MalScraper#10]
Node 10.6.0
Electron 2.0.5
```
TypeError: match is not a function
    at getResultsFromSearch.then (info.js?f8a3:154)
    at <anonymous>
```

**Comment by Kylart** [comment]
So it would seem that for some reason, `mal-scraper`'s dependencies were not correctly installed by your app. There are multiple reasons that would bring to this.

Your problem is that `match-sorter` is not being packaged / installed in your app.

So the best thing to do there would be to nuke your `node_modules` and maybe `package-lock.json` and run a `npm install` again.

**Comment by xdk78** [comment]
I did it twice, but problem still appears.
Maybe is related to `yarn`?

**Comment by Kylart** [comment]
What is your `npm` version and OS?

I tried again on Mac and Windows with and without `yarn` but still works 🤔

**Comment by Kylart** [comment]
Alright, some update on this as we never really understood when that problem came from.

It seems to be a problem related to using mal-scraper with Babel. When using Babel and importing `mal-scraper`, you get an error that `match is not a function`. While I don't really understand why, it seems to be the cause.

Hence, `v2.5.2` implement [a fix](https://github.com/Kylart/MalScraper/commit/3038d19f06f78deb8b0c8428ff34e6227f6a3002) where someone can pass a additional argument to use the so-called match function.

Please use `getInfoFromName` with a second argument set to `false` if you have that error.
