### ISSUE TITLE
No get all anime function/method

### ISSUE THREAD

**Issue by Marviuz** [Kylart/MalScraper#13]
I think there's no getAllAnimes function or anything similar that will get all animes that's in the API.

**Comment by Kylart** [comment]
Hello,

Well there is one given by the API which is implemented as described [here](https://github.com/Kylart/MalScraper/blob/master/README.md#search). 

Though, as the API is STILL down, I guess you'd want one that behaves like that but would not require the API ? This function exists as described [here](https://github.com/Kylart/MalScraper/blob/master/README.md#getresultsfromsearch).

**Comment by Marviuz** [comment]
What I meant is a function that will get all animes/mangas. For example, when the user clicks a link going to `Animes` or `Mangas`  then it will give them a list of all Animes/Mangas. Or, is there a trick with the use of the function you mentioned? I tried the `getResultsFromSearch('')` and `getResultsFromSearch(' ')` but it required me to have something inside of it.

**Comment by Kylart** [comment]
> I tried the getResultsFromSearch('') and getResultsFromSearch(' ') but it required me to have something inside of it.

`getResultsFromSearch` returns at most 10 results (because MAL gives only 10 results)

> For example, when the user clicks a link going to Animes or Mangas then it will give them a list of all Animes/Mangas then it will give them a list of all Animes/Mangas.

I'm not sure what you meant since I can't find a url that gives a list of all animes in one go except for `Top animes` ? [The anime search page](https://myanimelist.net/anime.php) gives you entries but based on genres.

My understanding is that you'd like something that gives you a list of all the anime / mangas that myanimelist has but such things do not exist, you'd have to crawl through a large part of the website while getting 429 errors (Too many requests) every 30 requests.

**Comment by Marviuz** [comment]
Oh I see. That's sad. Thank you for answering :)
